/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Diogo Semedo, Cláudio Alves
 */
public class AlterarLocais extends javax.swing.JPanel {
    private ListaElementos comunidade;
    private ListaLocais locais;
    private int indice;
    private javax.swing.JPanel jPainelPrincipal;
    private javax.swing.JPanel jPainelAnterior;
    private InterfaceProjeto I;
    /**
     * Creates new form AlterarLocais
     * @param comunidade Tipo : ListaElementos - ArrayList Elemento com a informação dos elementos e dos inscritos.
     * @param locais Tipo : ListaLocais - ArrayList Local com a informação dos locais.
     * @param indice Tipo : Integer - Indice do elemento na ListaInscritos ao qual vamos adicionar locais.
     * @param I Tipo : InterfaceProjeto - A Frame de todo o projeto, necessária para fazer alterações dos paineis.
     * @param jPainelAnterior Tipo : JPanel - Acesso ao painel anterior.
     * @param jPainelPrincipal Tipo : JPanel - Acesso ao painel principal. 
     */
    

    public AlterarLocais(ListaElementos comunidade, ListaLocais locais, int indice, JPanel jPainelPrincipal, JPanel jPainelAnterior, InterfaceProjeto I) {
        this.comunidade = comunidade;
        this.locais = locais;
        this.indice = indice;
        this.jPainelPrincipal = jPainelPrincipal;
        this.jPainelAnterior = jPainelAnterior;
        this.I = I;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        inscrever = new javax.swing.JButton();
        visualizar = new javax.swing.JButton();
        meusLocais = new javax.swing.JButton();
        minhaInfo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));
        setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(340, 90, 400, 240);

        voltar.setBackground(new java.awt.Color(141, 184, 184));
        voltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        add(voltar);
        voltar.setBounds(35, 390, 60, 25);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);

        String[] nomes = new String[locais.getListaLocais().size()+1];
        nomes[0]="Nenhum local.";
        for(int i=0;i<locais.getListaLocais().size();i++){
            nomes[i+1]=locais.getListaLocais().get(i).nome;
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(nomes));

        inscrever.setBackground(new java.awt.Color(141, 184, 184));
        inscrever.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inscrever.setForeground(new java.awt.Color(255, 255, 255));
        inscrever.setText("Inscrever");
        inscrever.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        inscrever.setContentAreaFilled(false);
        inscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscreverActionPerformed(evt);
            }
        });

        visualizar.setBackground(new java.awt.Color(141, 184, 184));
        visualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        visualizar.setForeground(new java.awt.Color(255, 255, 255));
        visualizar.setText("Visualizar inscritos/lotacao locais");
        visualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        visualizar.setContentAreaFilled(false);
        visualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });

        meusLocais.setBackground(new java.awt.Color(141, 184, 184));
        meusLocais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        meusLocais.setForeground(new java.awt.Color(255, 255, 255));
        meusLocais.setText("Os meus locais");
        meusLocais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        meusLocais.setContentAreaFilled(false);
        meusLocais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meusLocais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meusLocaisActionPerformed(evt);
            }
        });

        minhaInfo.setBackground(new java.awt.Color(141, 184, 184));
        minhaInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        minhaInfo.setForeground(new java.awt.Color(255, 255, 255));
        minhaInfo.setText("A minha informação");
        minhaInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        minhaInfo.setContentAreaFilled(false);
        minhaInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minhaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhaInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minhaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meusLocais, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(minhaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(meusLocais, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1);
        jPanel1.setBounds(65, 97, 225, 230);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Bem-vindo/a "+comunidade.getListaInscritos().get(indice).getNome());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(308, 308, 308))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        add(jPanel2);
        jPanel2.setBounds(0, 25, 800, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/fundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 450);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Esta ação serve para o utilizador ter acesso á informação de todos os locais disponíveis, na TextArea do painel.
    */
    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        for(int i=0;i<locais.getListaLocais().size();i++){
                jTextArea1.append(locais.getListaLocais().get(i).visualizar()+"\n");
       }
    }//GEN-LAST:event_visualizarActionPerformed
    /**
    * Esta ação serve para o utilizador ter acesso aos locais em que está inscrito, na TextArea do painel.
    */
    private void meusLocaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meusLocaisActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        for(int i=0;i<comunidade.getListaInscritos().get(indice).getLocais().size();i++){
            jTextArea1.append(comunidade.getListaInscritos().get(indice).getLocais().get(i).toString()+"\n");
        }
    }//GEN-LAST:event_meusLocaisActionPerformed
    /**
    * Esta ação serve para o utilizador poder retornar ao painel anterior.
    */
    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        this.I.getContentPane().removeAll();
        this.I.getContentPane().add(jPainelAnterior);
        this.I.revalidate();
        this.I.repaint();
    }//GEN-LAST:event_voltarActionPerformed
    /**
    * Esta ação serve para o utilizador poder adicionar um local á sua inscrição.
    * Seja uma inscrição válida ou não o utilizador fica sempre no painel até usar o botão voltar.
    */
    private void inscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscreverActionPerformed
        // TODO add your handling code here:
        String nome;
        nome = (String) jComboBox1.getSelectedItem();
        int ver=1;
        if(nome.equals("Nenhum local.")){
            ver=0;
        }
        for(int i=0;i<comunidade.getListaInscritos().get(indice).getLocais().size();i++){
            if(comunidade.getListaInscritos().get(indice).getLocais().get(i).getNome().equals(nome)){
                ver=-1;
            }
        }
        
        int value;
        if(ver==1){
            
            value=comunidade.alterarLocal(nome, indice, locais);
            if(value==1){
                try {
                    JOptionPane.showMessageDialog(this, "Inscrito com sucesso.");
                    comunidade.meteListaInscritos();
                    locais.meteLista();
                } catch (IOException ex) {
                    Logger.getLogger(AlterarLocais.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AlterarLocais.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(value==0){
               JOptionPane.showMessageDialog(this, "Já atingiu o número máximo de locais onde se pode inscrever."); 
            }
            else if(value==2){
                JOptionPane.showMessageDialog(this, "Pedimos desculpa mas o local em que se tentou inscrever, não está disponível."); 
            }
        }
        else if(ver==0){
           JOptionPane.showMessageDialog(this, "Para se inscrever deve selecionar pelo menos um local."); 
        }
        else if(ver==-1){
            JOptionPane.showMessageDialog(this, "Já se encontra inscrito neste local."); 
        }
    }//GEN-LAST:event_inscreverActionPerformed
    /**
    * Esta ação serve para o utilizador poder ter acesso á sua informação na TextArea do painel.
    */
    private void minhaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhaInfoActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea1.append("A minha informação:\n"+comunidade.getListaInscritos().get(indice).toInformacao());
        
        
    }//GEN-LAST:event_minhaInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inscrever;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton meusLocais;
    private javax.swing.JButton minhaInfo;
    private javax.swing.JButton visualizar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
