/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Diogo Semedo, Cláudio Alves
 */
public class Inscrever extends javax.swing.JPanel {
    private ListaElementos comunidade;
    private ListaLocais locais;
    private int indice;
    private javax.swing.JPanel jPainelPrincipal;
    private javax.swing.JPanel jPainelAnterior;
    private InterfaceProjeto I;
    /**
     * Creates new form Inscrever
     * @param comunidade Tipo : ListaElementos - ArrayList Elemento com a informação dos elementos e dos inscritos.
     * @param locais Tipo : ListaLocais - ArrayList Local com a informação dos locais.
     * @param indice Tipo : Integer - Indice do elemento na ListaElementos que vai ser copiado para a ListaInscritos.
     * @param jPainelPrincipal Tipo : JPanel - Acesso ao painel principal. 
     * @param jPainelAnterior Tipo : JPanel - Acesso ao painel anterior.
     * @param I Tipo : InterfaceProjeto - A Frame de todo o projeto, necessária para fazer alterações dos paineis.
     */
    public Inscrever(ListaElementos comunidade, ListaLocais locais,int indice, JPanel jPainelPrincipal,InterfaceProjeto I, JPanel jPainelAnterior) {
        this.comunidade = comunidade;
        this.locais = locais;
        this.indice = indice;
        this.jPainelPrincipal=jPainelPrincipal;
        this.jPainelAnterior=jPainelAnterior;
        this.I=I;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        Visualizar = new javax.swing.JButton();
        Inscrever = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));
        setLayout(null);

        jScrollPane1.setAutoscrolls(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleDescription("");

        add(jScrollPane1);
        jScrollPane1.setBounds(340, 80, 409, 260);

        Voltar.setBackground(new java.awt.Color(141, 184, 184));
        Voltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setText("Voltar");
        Voltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Voltar.setContentAreaFilled(false);
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        add(Voltar);
        Voltar.setBounds(35, 390, 60, 25);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(225, 270));

        String[] nomes = new String[locais.getListaLocais().size()+1];
        nomes[0]="Nenhum local.";
        for(int i=0;i<locais.getListaLocais().size();i++){
            nomes[i+1]=locais.getListaLocais().get(i).nome;
        }
        jComboBox1.setBackground(new java.awt.Color(141, 184, 184));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(nomes));

        jComboBox2.setBackground(new java.awt.Color(141, 184, 184));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(nomes));

        jComboBox3.setBackground(new java.awt.Color(141, 184, 184));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(nomes));

        jComboBox4.setBackground(new java.awt.Color(141, 184, 184));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(nomes));

        jComboBox5.setBackground(new java.awt.Color(141, 184, 184));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(nomes));

        Visualizar.setBackground(new java.awt.Color(141, 184, 184));
        Visualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Visualizar.setForeground(new java.awt.Color(255, 255, 255));
        Visualizar.setText("Visualizar inscritos/lotação locais"); // NOI18N
        Visualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Visualizar.setContentAreaFilled(false);
        Visualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarActionPerformed(evt);
            }
        });

        Inscrever.setBackground(new java.awt.Color(141, 184, 184));
        Inscrever.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Inscrever.setForeground(new java.awt.Color(255, 255, 255));
        Inscrever.setText("Inscrever");
        Inscrever.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Inscrever.setContentAreaFilled(false);
        Inscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscreverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        add(jPanel1);
        jPanel1.setBounds(53, 80, 230, 310);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Bem-vindo/a "+ comunidade.getListaElementos().get(indice).nome);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(305, 305, 305))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel2);
        jPanel2.setBounds(0, -300, 800, 367);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/fundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 450);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Esta ação serve para o utilizador se Inscrever nos locais selecionados nas "ComboBoxs".
    */
    private void InscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscreverActionPerformed
        
        String[] aux=new String[5];
        aux[0]= (String) jComboBox1.getSelectedItem();
        aux[1]= (String) jComboBox2.getSelectedItem();
        aux[2]= (String) jComboBox3.getSelectedItem();
        aux[3]= (String) jComboBox4.getSelectedItem();
        aux[4]= (String) jComboBox5.getSelectedItem();
        /*´tirar repetidos*/
        int conta=0;
        //conta os locais invalidos
        for(int i=0;i<5;i++){
            if(aux[i].equals("Nenhum local.")){
                conta++;
            }
            for(int j = i+1;j<5;j++){
                if(aux[i].equals(aux[j])){
                    aux[j]="Nenhum local.";
                }
            }
        }
        // -1 já foi inscrito  1 inscreveu e adicionou local
        int value;
        if(conta<5){
            value=comunidade.inscrever(aux, indice, locais);
            if(value==1){
                try {
                    JOptionPane.showMessageDialog(this, "Inscrito com sucesso.");
                    comunidade.meteListaInscritos();
                    locais.meteLista();
                    this.I.getContentPane().removeAll();
                    this.I.getContentPane().add(jPainelPrincipal);
                    this.I.revalidate();
                    this.I.repaint();
                } catch (IOException ex) {
                    Logger.getLogger(Inscrever.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Inscrever.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(value==-1){
                JOptionPane.showMessageDialog(this, "Já se encontra inscrito!");
                this.I.getContentPane().removeAll();
                this.I.getContentPane().add(jPainelPrincipal);
                this.I.revalidate();
                this.I.repaint();
            }
            else if(value==0){
                JOptionPane.showMessageDialog(this, "Pedimos desculpa mas os locais ou local em que se tentou inscrever, não estão disponíveis."); 
            }
        }
        else{
           JOptionPane.showMessageDialog(this, "Para se inscrever deve selecionar pelo menos um local."); 
        }
    }//GEN-LAST:event_InscreverActionPerformed

    
    /**
    * Esta ação serve para o utilizador ter acesso aos dados dos locais disponíveis.
    */
    private void VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarActionPerformed
        jTextArea1.setText("");
        for(int i=0;i<locais.getListaLocais().size();i++){
                jTextArea1.append(locais.getListaLocais().get(i).visualizar()+"\n");
       }
    }//GEN-LAST:event_VisualizarActionPerformed

    
    
    /**
    * Esta ação serve para o utilizador poder retornar ao painel anterior.
    */
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        this.I.getContentPane().removeAll();
        this.I.getContentPane().add(jPainelAnterior);
        this.I.revalidate();
        this.I.repaint();
    }//GEN-LAST:event_VoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inscrever;
    private javax.swing.JButton Visualizar;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
