/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diogo Semedo, Cláudio Alves
 */
public class InterfaceProjeto extends javax.swing.JFrame{
    private ListaElementos comunidade;
    private ListaLocais locais;
    /**
     * Construtor do form InterfaceProjeto
     */
    public InterfaceProjeto(){
        this.comunidade=new ListaElementos();
        this.locais = new ListaLocais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EntrarConta = new javax.swing.JButton();
        SeriarLocais = new javax.swing.JButton();
        InfoGeral = new javax.swing.JButton();
        MostrarGuest = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 450));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 450));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 450));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serão de Convívio de POO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(162, 162, 162))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 34, 800, 90);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);

        EntrarConta.setBackground(new java.awt.Color(141, 184, 184));
        EntrarConta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EntrarConta.setForeground(new java.awt.Color(255, 255, 255));
        EntrarConta.setText("Entrar na conta");
        EntrarConta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        EntrarConta.setContentAreaFilled(false);
        EntrarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EntrarConta.setMaximumSize(new java.awt.Dimension(120, 30));
        EntrarConta.setMinimumSize(new java.awt.Dimension(120, 30));
        EntrarConta.setPreferredSize(new java.awt.Dimension(120, 30));
        EntrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarContaActionPerformed(evt);
            }
        });

        SeriarLocais.setBackground(new java.awt.Color(141, 184, 184));
        SeriarLocais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SeriarLocais.setForeground(new java.awt.Color(255, 255, 255));
        SeriarLocais.setText("Seriação Locais");
        SeriarLocais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        SeriarLocais.setContentAreaFilled(false);
        SeriarLocais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeriarLocais.setPreferredSize(new java.awt.Dimension(120, 30));
        SeriarLocais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeriarLocaisActionPerformed(evt);
            }
        });

        InfoGeral.setBackground(new java.awt.Color(141, 184, 184));
        InfoGeral.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        InfoGeral.setForeground(new java.awt.Color(255, 255, 255));
        InfoGeral.setText("Informação geral");
        InfoGeral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        InfoGeral.setContentAreaFilled(false);
        InfoGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoGeral.setPreferredSize(new java.awt.Dimension(120, 30));
        InfoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoGeralActionPerformed(evt);
            }
        });

        MostrarGuest.setBackground(new java.awt.Color(255, 255, 255));
        MostrarGuest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MostrarGuest.setForeground(new java.awt.Color(255, 255, 255));
        MostrarGuest.setText("GuestList");
        MostrarGuest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        MostrarGuest.setContentAreaFilled(false);
        MostrarGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarGuest.setPreferredSize(new java.awt.Dimension(120, 30));
        MostrarGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGuestActionPerformed(evt);
            }
        });

        int tam=0;
        for(int i=0;i<locais.getListaLocais().size();i++){
            if(locais.getListaLocais().get(i) instanceof Bar){
                tam++;
            }
        }
        String[] nomes = new String[tam];
        for(int i=0;i<locais.getListaLocais().size();i++){
            if(locais.getListaLocais().get(i) instanceof Bar){
                nomes[i]=locais.getListaLocais().get(i).getNome();
            }
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(nomes));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setPreferredSize(new java.awt.Dimension(120, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 131, Short.MAX_VALUE)
                    .addComponent(MostrarGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SeriarLocais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EntrarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(EntrarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SeriarLocais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MostrarGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(74, 150, 170, 220);

        jTextArea1.setOpaque(false);
        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setMaximumSize(new java.awt.Dimension(150, 40));
        jTextArea1.setMinimumSize(new java.awt.Dimension(150, 40));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(266, 150, 430, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/fundo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 450));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 450));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 450));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 450);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Esta ação serve para o utilizador ter acesso aos dados das GuestList, na TextArea do painel.
    */
    private void MostrarGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGuestActionPerformed
        // TODO add your handling code here:
        String nome;
        nome = (String) jComboBox1.getSelectedItem();
        jTextArea1.setText("");
        for(int i=0;i<locais.getListaLocais().size();i++){
            if(locais.getListaLocais().get(i).getNome().equals(nome)){
                for(int j=0;j<((Bar)locais.getListaLocais().get(i)).getGuest().getGuestList().size();j++){
                    jTextArea1.append(((Bar)locais.getListaLocais().get(i)).getGuest().getGuestList().get(j).toString()+"\n");
                }
            }
        }
    }//GEN-LAST:event_MostrarGuestActionPerformed

    
    /**
    * Esta ação serve para o utilizador ter acesso à informação geral do programa, na TextArea do painel.
    */
    private void InfoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoGeralActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea1.append("Valor da receita: "+comunidade.getReceita()+" € \n");
        jTextArea1.append("Número total de inscritos: "+comunidade.getListaInscritos().size()+"\n");
        jTextArea1.append("Número total de inscrições em locais: "+locais.totalInscritos()+"\n");
        locais.ordenar();
        jTextArea1.append("Local favorito: "+locais.getListaLocais().get(0).getNome()+"\n");
    }//GEN-LAST:event_InfoGeralActionPerformed

    
    
    /**
    * Esta ação serve para o utilizador ter acesso aos dados de todos os locais disponíveis, na TextArea do painel.
    */
    private void SeriarLocaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeriarLocaisActionPerformed
        // TODO add your handling code here:
        locais.ordenar();
        jTextArea1.setText("");
        for(int i=0;i<locais.getListaLocais().size();i++){
            jTextArea1.append(locais.getListaLocais().get(i).visualizar()+"\n");
        }
    }//GEN-LAST:event_SeriarLocaisActionPerformed

    
    /**
    * Esta ação serve para o utilizador ter acesso à página de Registar/Login.
    */
    private void EntrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarContaActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        this.getContentPane().removeAll();
        this.getContentPane().add(new PainelInscricao(this.comunidade,this.locais,this,this.jPanel2));
        this.revalidate();
    }//GEN-LAST:event_EntrarContaActionPerformed

    /**
     * Método usado para carregar as ArrayList que têm de ser carregadas antes dos componentes da Interface Gráfica serem iniciados,
     * ArrayList estas que são necessárias para o bom funcionamento do programa.
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     * @throws java.awt.FontFormatException
     */
    public static void main(String args[]) throws IOException, ClassNotFoundException, FontFormatException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        InterfaceProjeto I= new InterfaceProjeto();
        I.setResizable(false);
        I.locais.carregarFicheiroTexto();
        I.comunidade.carregarFicheiroTexto();
        I.locais.carregarLista();
        I.comunidade.carregarLista();
        I.comunidade.carregarListaInscritos();
        I.comunidade.calcularReceita();
        I.comunidade.meteLista();
        I.initComponents();
        I.setTitle("Serão de Convívio POO");
        /* Create and display the form*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           I.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntrarConta;
    private javax.swing.JButton InfoGeral;
    private javax.swing.JButton MostrarGuest;
    private javax.swing.JButton SeriarLocais;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
