/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;


import java.awt.LayoutManager;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Diogo Semedo, Cláudio Alves
 */
public class PainelInscricao extends javax.swing.JPanel {

 
    private ListaElementos comunidade;
    private ListaLocais locais;
    private InterfaceProjeto I;
    private javax.swing.JPanel jPainelPrincipal;

    /**
     * Construtor do form PainelInscricao
     * @param comunidade Tipo : ListaElementos - ArrayList Elemento com a informação dos elementos e dos inscritos.
     * @param locais Tipo : ListaLocais - ArrayList Local com a informação dos locais.
     * @param I Tipo : InterfaceProjeto - A Frame de todo o projeto, necessária para fazer alterações dos paineis.
     * @param jPainelPrincipal Tipo : JPanel - Acesso ao painel principal. 
     */
    public PainelInscricao(ListaElementos comunidade, ListaLocais locais,InterfaceProjeto I, JPanel jPainelPrincipal) {
        initComponents();
        this.comunidade = comunidade;
        this.locais = locais;
        this.I= I;
        this.jPainelPrincipal=jPainelPrincipal;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 450));
        jPanel1.setLayout(null);

        registar.setBackground(new java.awt.Color(141, 184, 184));
        registar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registar.setForeground(new java.awt.Color(255, 255, 255));
        registar.setText("Registar");
        registar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        registar.setContentAreaFilled(false);
        registar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarActionPerformed(evt);
            }
        });
        jPanel1.add(registar);
        registar.setBounds(196, 302, 120, 30);

        voltar.setBackground(new java.awt.Color(255, 255, 255));
        voltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(35, 390, 60, 25);

        login.setBackground(new java.awt.Color(141, 184, 184));
        login.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        login.setContentAreaFilled(false);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(482, 302, 120, 30);

        jPanel2.setBackground(new java.awt.Color(141, 184, 184));
        jPanel2.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(141, 184, 184));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Palavra-chave :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(196, 130, 406, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/fundo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 450);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Esta ação serve para o utilizador entrar no painel em que se vai inscrever em locais pela primeira vez.
    * O utilizador só avança para o próximo painel, se tiver inserido o seu id e a password corretamente e se ainda não se tiver registado anteriormente.
    */
    private void registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarActionPerformed
        // TODO add your handling code here:
        int ver = 0;
        for(int i=0;i<comunidade.getListaElementos().size();i++){
            if(jTextField1.getText().equals(String.valueOf(comunidade.getListaElementos().get(i).getId()))){
                if(jPasswordField1.getText().equals((comunidade.getListaElementos().get(i).getPassword()))){
                    for(int j=0;j<comunidade.getListaInscritos().size();j++){
                        if(comunidade.getListaInscritos().get(j).getId()==comunidade.getListaElementos().get(i).getId()){
                            ver=-1;
                        }
                    }
                    if(ver!=-1){
                        jPasswordField1.setText("");
                        jTextField1.setText("");
                        this.I.getContentPane().removeAll();
                        this.I.getContentPane().add(new Inscrever(this.comunidade,this.locais,i,jPainelPrincipal,this.I,this));
                        this.I.revalidate();
                        ver = 1;
                    }
                }
            }
        }
        if(ver==0){
            JOptionPane.showMessageDialog(this, "Número de estudante ou palavra-chave inválidos!");
            jPasswordField1.setText("");
            jTextField1.setText("");
        }
        else if(ver==-1){
            JOptionPane.showMessageDialog(this, "Já se encontra registado, efetue login se o pretender.");
            jPasswordField1.setText("");
            jTextField1.setText("");
        }
        
    }//GEN-LAST:event_registarActionPerformed
    /**
    * Esta ação serve para o utilizador poder retornar ao painel anterior.
    */
    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        this.I.getContentPane().removeAll();
        this.I.getContentPane().add(jPainelPrincipal);
        this.I.revalidate();
        this.I.repaint();
    }//GEN-LAST:event_voltarActionPerformed

    /**
    * Esta ação serve para o utilizador poder entrar na sua conta e poder adicionar locais à sua inscrição.
    * O utilizador só avança para o próximo painel, se tiver inserido o seu id e a password corretamente e se já estiver registado.
    */
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        int ver = 0;
        for(int i=0;i<comunidade.getListaInscritos().size();i++){
            if(jTextField1.getText().equals(String.valueOf(comunidade.getListaInscritos().get(i).getId()))){
                ver=1;
            }
        }
        if(ver==1){
            for(int i=0;i<comunidade.getListaInscritos().size();i++){
                if(jTextField1.getText().equals(String.valueOf(comunidade.getListaInscritos().get(i).getId()))){
                    ver=-1;
                    if(jPasswordField1.getText().equals((comunidade.getListaInscritos().get(i).getPassword()))){
                            ver=1;
                            jPasswordField1.setText("");
                            jTextField1.setText("");
                            this.I.getContentPane().removeAll();
                            this.I.getContentPane().add(new AlterarLocais(this.comunidade,this.locais,i,jPainelPrincipal,this,this.I));
                            this.I.revalidate();
                            
                    }
                }
            }
        }
        else if(ver==0){
            JOptionPane.showMessageDialog(this, "Não se encontra registado.");
            jPasswordField1.setText("");
            jTextField1.setText("");
        }
        else if(ver==-1){
            JOptionPane.showMessageDialog(this, "Número de estudante ou palavra-chave inválidos.");
            jPasswordField1.setText("");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton login;
    private javax.swing.JButton registar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
